name: Semantic Release

on:
  push:
    branches:
      - main
      - dev

jobs:
  automatic_version_release:
    name: Automatic Version Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
    permissions:
      contents: write
      issues: write
      pull-requests: write
    env:
      RELEASE_VERSION: ""
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Java 18
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '18'
      - name: Setup Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Node.js Dependencies
        run: yarn install --frozen-lockfile --ignore-scripts
      - name: Test file
        run: touch test.js
      - name: Archive test.js artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-js-artifact
          path: test.js
      - name: Set Semantic Release Version (hacky)
        run: |
          RELEASE_VERSION=$(npx semantic-release --dry-run | grep 'The next release version is' | sed -E 's/.* ([[:digit:].]+)$/\1/')
          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Releasing on version
        run: echo ${{ env.RELEASE_VERSION }}
      # - name: Semantic Release
      #   run: npx semantic-release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish_android_debug_apk_release:
    name: Automatic Android Debug APK Publish Release
    runs-on: ubuntu-latest
    if: ${{ needs.automatic_version_release.result == 'success' }}
    needs: [automatic_version_release]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Download test.js artifact
        uses: actions/download-artifact@v4
        with:
          name: test-js-artifact
      - name: Publish APK
        run: gh release upload $RELEASE_VERSION test.js
        env:
          RELEASE_VERSION: ${{ needs.automatic_version_release.outputs.release_version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}